# Generated by Django 2.2.16 on 2023-04-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinylinks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tinylink',
            index=models.Index(fields=['short_url'], name='tinylinks_t_short_u_ee1953_idx'),
        ),
        migrations.AddIndex(
            model_name='tinylink',
            index=models.Index(fields=['long_url'], name='tinylinks_t_long_ur_99d4a0_idx'),
        ),
    ]
