name: Tox tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Install coverage
        run: pip install coverage
      
      - name: Run tox with coverage
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - name: Generate coverage JSON
        run: coverage json
      - name: Install urllib3 to get badge.
        run: pip install urllib3
      - name: Generate badge.
        run: python coveragebadgegen.py
